---
version: "3"
services:
  sn2ssg-go:
    container_name: sn2ssg-go
    image: toozej/sn2ssg-go:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.sn2ssg-go.rule=Host(`sn2ssg-go.test`)"
      # - "traefik.http.routers.sn2ssg-go.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.sn2ssg-go-secure.entrypoints=https"
      # - "traefik.http.routers.sn2ssg-go-secure.rule=Host(`sn2ssg-go.test`)"
      # - "traefik.http.routers.sn2ssg-go-secure.middlewares=headers@file"
      # - "traefik.http.routers.sn2ssg-go-secure.tls=true"
    # networks:
      # - traefik
